# permissions for end users to view natscoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: natsco-viewer-role
rules:
- apiGroups:
  - ceco.board.io
  resources:
  - natscoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ceco.board.io
  resources:
  - natscoes/status
  verbs:
  - get
