# permissions for end users to edit natscoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: natsco-editor-role
rules:
- apiGroups:
  - ceco.board.io
  resources:
  - natscoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceco.board.io
  resources:
  - natscoes/status
  verbs:
  - get
